<a href="https://colab.research.google.com/github/surrrender/PraticalAI/blob/main/notebooks/02_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

<img src="https://raw.githubusercontent.com/LisonEvf/practicalAI-cn/master/images/logo.png" width=150>

在本课中，我们将学习使用NumPy包进行数值分析的基础知识。

<img src="https://raw.githubusercontent.com/LisonEvf/practicalAI-cn/master/images/numpy.png" width=300>




# NumPy 基础知识

In [ ]:
import numpy as np

In [ ]:
# 使得多次生成的随机数相同
np.random.seed(seed=1234)

In [ ]:
# 标量（scalars）
x = np.array(6) # scalar
print ("x: ", x)
print("x ndim: ", x.ndim) #展示的是数组的维数 number of dimensions
print("x shape:", x.shape) #represents the size of each dimension of the array,意思是每个维度上的大小
print("x size: ", x.size) #数组中总的元素数量
print ("x dtype: ", x.dtype) #数组中元素的tpye

x:  6
x ndim:  0
x shape: ()
x size:  1
x dtype:  int64


In [ ]:
# 一维数组（array）
x = np.array([1.3 , 2.2 , 1.7])
print ("x: ", x)
print("x ndim: ", x.ndim) #为什么是1，因为只是一维数组，即数组只有一行
print("x shape:", x.shape)
print("x size: ", x.size)
print ("x dtype: ", x.dtype) # notice the float datatype

x:  [1.3 2.2 1.7]
x ndim:  1
x shape: (3,)
x size:  3
x dtype:  float64


In [ ]:
# 三维数组（矩阵（matrix））
x = np.array([[[1,2,3], [4,5,6], [7,8,9]]])# 最外层意味着这是一个矩阵，第二层意味着矩阵有三行，第三层意味着每行有三列
print ("x:\n", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)# The shape is represented as a tuple, indicating the size of each dimension
print("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
x ndim:  3
x shape: (1, 3, 3)
x size:  9
x dtype:  int64


In [ ]:
# 函数
# This part of the code demonstrates the use of some built-in functions from the numpy library to create arrays:
print ("np.zeros((2,2)):\n", np.zeros((2,2)))
print ("np.ones((2,2)):\n", np.ones((2,2)))
print ("np.eye((2)):\n", np.eye((2)))# create a 2x2 identity matrix.
print ("np.random.random((2,2)):\n", np.random.random((2,2)))

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye((2)):
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2)):
 [[0.19151945 0.62210877]
 [0.43772774 0.78535858]]


# 索引

In [ ]:
# 索引（indexing）
x = np.array([1, 2, 3])
print ("x[0]: ", x[0])
x[0] = 0
print ("x: ", x)

x[0]:  1
x:  [0 2 3]


In [ ]:
# 切片（slicing）
# 展示了如何截取一个矩阵
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (x)
print ("x column 1: ", x[:, 1])
print ("x row 0: ", x[0, :])
print ("x rows 0,1,2 & cols 1,2: \n", x[:3, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1,2 & cols 1,2: 
 [[ 2  3]
 [ 6  7]
 [10 11]]


In [ ]:
# 整数数组索引，相当于用坐标来获取值
print (x)
rows_to_get = np.arange(len(x))
print ("rows_to_get: ", rows_to_get)# 要获取各个元素所在的行数
cols_to_get = np.array([0, 2, 1])
print ("cols_to_get: ", cols_to_get)# 要获取各个元素所在的列数
print ("indexed values: ", x[rows_to_get, cols_to_get])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rows_to_get:  [0 1 2]
cols_to_get:  [0 2 1]
indexed values:  [ 1  7 10]


In [ ]:
# 布尔数组索引，只掉挑选出符合特定条件的元素
x = np.array([[1,2], [3, 4], [5, 6]])
print ("x:\n", x)
print ("x > 2:\n", x > 2)# 这里的x>2像是一种判断条件
print ("x[x > 2]:\n", x[x > 2])# 而x[x > 2]就是使用这个条件去提取符合条件的元素

x:
 [[1 2]
 [3 4]
 [5 6]]
x > 2:
 [[False False]
 [ True  True]
 [ True  True]]
x[x > 2]:
 [3 4 5 6]


# 数组基础知识

In [ ]:
# 数学基础
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[1,2], [3,4]], dtype=np.float64)
print ("x + y:\n", np.add(x, y)) # or x + y
print ("x - y:\n", np.subtract(x, y)) # or x - y
print ("x * y:\n", np.multiply(x, y)) # or x * y

x + y:
 [[2. 4.]
 [6. 8.]]
x - y:
 [[0. 0.]
 [0. 0.]]
x * y:
 [[ 1.  4.]
 [ 9. 16.]]


<img src="https://raw.githubusercontent.com/LisonEvf/practicalAI-cn/master/images/matrix.png" width=400>


In [ ]:
# 点积
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64) # 我们可以指定dtype
b = np.array([[7,8], [9,10], [11, 12]], dtype=np.float64)
print (a.dot(b))

[[ 58.  64.]
 [139. 154.]]


In [ ]:
# 跨维度求和
x = np.array([[1,2],[3,4]])
print (x)
print ("sum all: ", np.sum(x)) # 将所有元素相加
print ("sum by col: ", np.sum(x, axis=0)) # 逐列将元素相加
print ("sum by row: ", np.sum(x, axis=1)) # 逐行将元素相加

[[1 2]
 [3 4]]
sum all:  10
sum by col:  [4 6]
sum by row:  [3 7]


In [ ]:
# 转置
print ("x:\n", x)
print ("x.T:\n", x.T)

x:
 [[1 2]
 [3 4]]
x.T:
 [[1 3]
 [2 4]]


# 数组高级知识

In [ ]:
# np.tile：重复维度
x = np.array([[1,2], [3,4]])
y = np.array([5, 6])
# tile函数的用法就是用重复指定的数组来生成新的矩阵，第一个参数为要重复的数组，第二个参数tuple为指定在行和列方向上要重复的次数
addent = np.tile(y, (len(x), 1))
print ("addent: \n", addent)
z = x + addent
print ("z:\n", z)

addent: 
 [[5 6]
 [5 6]]
z:
 [[ 6  8]
 [ 8 10]]


In [ ]:
# 广播（broadcasting），强制将一个数组转化为可以运算的情况
x = np.array([[1,2], [3,4]])
y = np.array([5, 6])
z = x + y
print ("z:\n", z)

z:
 [[ 6  8]
 [ 8 10]]


In [ ]:
# 改变维度，强制转化格式
x = np.array([[1,2], [3,4], [5,6]])
print (x)
print ("x.shape: ", x.shape)
y = np.reshape(x, (2, 3))
print ("y.shape: ", y.shape)
print ("y: \n", y)

[[1 2]
 [3 4]
 [5 6]]
x.shape:  (3, 2)
y.shape:  (2, 3)
y: 
 [[1 2 3]
 [4 5 6]]


In [ ]:
# 删除维度
x = np.array([[[1,2,1]],[[2,2,3]]])
print ("x.shape: ", x.shape)
y = np.squeeze(x, 1) # 删除维度1
print ("y.shape: ", y.shape)
print ("y: \n", y)

x.shape:  (2, 1, 3)
y.shape:  (2, 3)
y: 
 [[1 2 1]
 [2 2 3]]


In [ ]:
# 添加维度
x = np.array([[1,2,1],[2,2,3]])
print ("x.shape: ", x.shape)
y = np.expand_dims(x, 1) # 扩展维度1
print ("y.shape: ", y.shape)
print ("y: \n", y)

x.shape:  (2, 3)
y.shape:  (2, 1, 3)
y: 
 [[[1 2 1]]

 [[2 2 3]]]


# 其它资源

你不必熟悉本文中任何东西，因为我们将在后面的课程中仔细研究NumPy。如果你对Numpy感到好奇，可以自行查看 [NumPy reference manual](https://docs.scipy.org/doc/numpy-1.15.1/reference/).